### ISSUE TITLE
App crashes when the current player does not have any valid moves

### ISSUE THREAD

**Issue by bregmi1** [cschilli/checkers-android#7]
Instead of showing the game over dialog box the game crashes when the player does not have a valid move.

**Comment by cschilli** [comment]
Confirmed bug for vs Computer mode as well. Once the computer runs out of moves (ie the last piece becomes surrounded by pieces it cannot capture) the game just crashes instead of giving a game over screen.

**Comment by bregmi1** [comment]
Fixed it. But needs more testing.
